const Data = [
  {
    id: 1,
    withoutCard: "Нет в наличии",
    description: "Вариативный замок Golden Soft для отеля",
    price: "7 000₽",
    discount: "8 000₽",
    check: '<img src="./images/nocheck.png" alt="">',
    image: '<img src="./images/1card.png" alt="" />',
  },
  {
    id: 2,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "33 000₽",
    discount: "39 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/2card.png" alt="" />',
  },
  {
    id: 3,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "9 000₽",
    discount: "12 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/3card.png" alt="" />',
  },
  {
    id: 4,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "9 000₽",
    discount: "12 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/3card.png" alt="" />',
  },
  {
    id: 5,
    withoutCard: "Нет в наличии",
    description: "Вариативный замок Golden Soft для отеля",
    price: "7 000₽",
    discount: "8 000₽",
    check: '<img src="./images/nocheck.png" alt="">',
    image: '<img src="./images/1card.png" alt="" />',
  },
  {
    id: 6,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "33 000₽",
    discount: "39 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/2card.png" alt="" />',
  },
  {
    id: 7,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "9 000₽",
    discount: "12 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/3card.png" alt="" />',
  },
  {
    id: 8,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "33 000₽",
    discount: "39 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/2card.png" alt="" />',
  },
  {
    id: 9,
    withoutCard: "Нет в наличии",
    description: "Вариативный замок Golden Soft для отеля",
    price: "7 000₽",
    discount: "8 000₽",
    check: '<img src="./images/nocheck.png" alt="">',
    image: '<img src="./images/1card.png" alt="" />',
  },
  {
    id: 10,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "33 000₽",
    discount: "39 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/2card.png" alt="" />',
  },
  {
    id: 11,
    withoutCard: "В наличии",
    description: "Дверной Замок Golden Soft для офиса",
    price: "9 000₽",
    discount: "12 000₽",
    check: '<img src="./images/checked.png" alt="">',
    image: '<img src="./images/3card.png" alt="" />',
  },
  {
    id: 12,
    withoutCard: "Нет в наличии",
    description: "Вариативный замок Golden Soft для отеля",
    price: "7 000₽",
    discount: "8 000₽",
    check: '<img src="./images/nocheck.png" alt="">',
    image: '<img src="./images/1card.png" alt="" />',
  },
];
export { Data };
